name: Lint PR

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-24.04
    steps:
      - uses: amannn/action-semantic-pull-request@v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Must match types in release-please-config.json
          types: |
            feat
            fix
            perf
            refactor
            style
            build
            docs
            chore
            test
            ci
            revert
            release
          scopes: |
            cli
            docker
            notion
            sync
            store
            webhook
            deps
            docs
            ci
            release
            logging
          requireScope: false
